# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a519076550329a0ade2aa7f525aa35d7a1a2fd93165aeb7a5c39841555a7bb36948d4851f2b9779123807e1a1f23bdc1aa256359f20577f46c2bc4dfd41a1270

test:
  secret_key_base: e65e93230671d364013e7349d13aef031c739bbee79dfa3d51ab6efad95cc8a40eaafb87a6595cb8bf47c8ee81b304b07a5f56763b62759c4a4711586c2c5e15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a519076550329a0ade2aa7f525aa35d7a1a2fd93165aeb7a5c39841555a7bb36948d4851f2b9779123807e1a1f23bdc1aa256359f20577f46c2bc4dfd41a1270
